feat(haveged): add haveged
grid-x/images pull request #27
Opened 2018-08-08 09:19 UTC by philippfranke

2018-08-08 13:49 UTC, gq0 requested changes

2018-08-08 13:49 UTC, gq0 commented on images/haveged/Dockerfile
> +FROM arm32v6/alpine:3.7
Actually we have a armv7 but could you use 
```FROM multiarch/debian-debootstrap:armhf-stretch-slim```

2018-08-14 12:26 UTC, gq0 commented on images/haveged/Dockerfile
> +FROM arm32v6/alpine:3.7
to make the system aware of arm binaries and to use qemu:
`docker run --rm --privileged multiarch/qemu-user-static:register --reset`

2018-08-23 08:44 UTC, jhedev commented
@philippfranke are you going to fix this?

2018-08-28 07:30 UTC, jhedev commented
@philippfranke are you going to update this or should we close it?

2018-08-28 07:30 UTC, jhedev commented
you updated it already :D sorry. Zube doesn't show that.

2018-08-28 07:30 UTC, jhedev requested changes

2018-08-28 07:30 UTC, jhedev commented on images/haveged/Dockerfile
> +	rm -rf /var/lib/apt/lists/*
weird formatting. pls fix it.

2018-08-28 07:30 UTC, jhedev commented
@gq0 please have a look again

2018-08-28 10:39 UTC, gq0 commented on images/haveged/Dockerfile
> +ENTRYPOINT ["/usr/sbin/haveged", "-F"]
I am not sure what the default number of bits but maybe add `-w 1024` to be sure.

2018-09-04 14:49 UTC, jhedev approved these changes

2018-09-04 15:11 UTC, gq0 approved these changes

2018-09-04 15:33 UTC, merged